name: Test My Action

on:
  pull_request:
    branches:
      - "**"   # any target branch
  push:
    branches:
      - "**"    

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ===================================================================
      # IMPORTANT: This is where you use your action.
      #
      # Replace 'YOUR_USERNAME/YOUR_REPOSITORY_NAME@v1' below with the
      # identifier of your action from the GitHub Marketplace.
      # For example: 'actions/setup-node@v3'
      # ===================================================================
      - name: Run My Custom Action
        uses: vishnudas111/pmat-action@v1.0.1
        with:
          max-cyclomatic: 20
          fail-on-violation: true
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run a test script
        run: node index.js
